# a docker-compose file with a postgres 14 service

version: '3.8'
services:
  contort:
    build:
        context: .
        dockerfile: ./dockerfiles/Dockerfile
    container_name: contort
    ports:
      - "8000:8000"
    environment:
        - POSTGRES_NAME=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=dbct
        - REDIS_HOST=redisct
        - CORS_ORIGIN_WHITELIST=http://localhost,http://localhost:4200
        - ALLOWED_HOSTS=localhost
    networks:
      - ct-net

  dbct:
    container_name: dbct
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
    networks:
      - ct-net
  redisct:
    container_name: redisct
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-redis
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    networks:
      - ct-net

networks:
    ct-net:
