# Generated by Django 5.0 on 2023-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_rename_consurf_msa_variantion_consurfmodel_consurf_msa_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consurfmodel',
            name='uniprot_accession',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
