# Generated by Django 5.1.4 on 2025-01-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0005_proteinfastadatabase_consurfjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='error_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='log_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='process_cmd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proteinfastadatabase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
