# Generated by Django 5.1.4 on 2025-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0007_consurfmodel_consurf_job_consurfmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='closest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='cutoff',
            field=models.FloatField(default=0.0001),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='max_homologs',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='max_id',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='max_iterations',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='maximum_likelihood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='min_id',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='consurfjob',
            name='substitution_model',
            field=models.CharField(default='BEST', max_length=255),
        ),
    ]
