# Generated by Django 5.1.4 on 2025-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0008_consurfjob_closest_consurfjob_cutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='algorithm',
            field=models.CharField(default='HMMER', max_length=255),
        ),
    ]
