# Generated by Django 5.1.4 on 2025-01-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0009_consurfjob_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
