# Generated by Django 5.1.4 on 2025-01-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0013_consurfjob_chain_structurefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consurfjob',
            name='alignment_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consurfjob',
            name='query_sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
