# Generated by Django 5.1.4 on 2025-01-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0014_alter_consurfjob_alignment_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='query_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
