# Generated by Django 5.1.4 on 2025-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0015_consurfjob_query_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
