# Generated by Django 5.1.4 on 2025-01-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0016_consurfjob_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consurfjob',
            options={'ordering': ['-id']},
        ),
    ]
