# Generated by Django 5.1.4 on 2025-11-04 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ct', '0017_alter_consurfjob_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinfastadatabase',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proteinfastadatabase',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_fasta_databases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiplesequencealignment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplesequencealignment',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_msas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structurefile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structurefile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_structures', to=settings.AUTH_USER_MODEL),
        ),
    ]
