# Generated by Django 5.1.4 on 2025-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0018_add_file_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='consurfjob',
            name='rq_job_id',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
