# Generated by Django 5.1.4 on 2026-04-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct", "0019_add_rq_job_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="consurfjob",
            name="is_nucleotide",
            field=models.BooleanField(default=False),
        ),
    ]
