# Generated by Django 5.1.4 on 2026-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct", "0020_consurfjob_is_nucleotide"),
    ]

    operations = [
        migrations.AddField(
            model_name="proteinfastadatabase",
            name="blast_index_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("building", "Building"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="proteinfastadatabase",
            name="mmseqs_index_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("building", "Building"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
