FROM noatgnu/consurf-alone:bookworm

WORKDIR /app
RUN mkdir "/app/media"
RUN mkdir "/app/staticfiles"
RUN mkdir "/app/backup"
COPY . /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["python", "manage.py", "rqworker"]
