FROM noatgnu/consurf-alone:0.0.2

WORKDIR /app
RUN mkdir "/app/media"
RUN mkdir "/app/staticfiles"
RUN mkdir "/app/backup"
COPY . /app/

RUN /opt/miniconda/bin/conda run -n consurf_env pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["/opt/miniconda/bin/conda", "run", "-n", "consurf_env", "python", "manage.py", "rqworker"]