FROM noatgnu/consurf-alone:0.0.2

RUN sed -i 's|mafft --localpair --maxiterate 1000 --quiet --threads 20|mafft --localpair --maxiterate 1000 --quiet --thread 5|g' /workspace/stand_alone_consurf/stand_alone_consurf.py
WORKDIR /app
RUN mkdir "/app/media"
RUN mkdir "/app/staticfiles"
RUN mkdir "/app/backup"
COPY . /app/

RUN /opt/miniconda/bin/conda run -n consurf_env pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8000
ENTRYPOINT ["/opt/miniconda/bin/conda", "run", "-n", "consurf_env", "--no-capture-output"]
CMD ["python", "manage.py", "rqworker"]