FROM node:20-bookworm-slim

ARG BUILD_DATE
ENV API_HOST=contort.proteo.nexus

WORKDIR /app
RUN apt update
RUN apt -y upgrade
RUN apt install -y git
RUN git clone https://github.com/noatgnu/Contort.git

RUN sed -i "s;https://contort.captain.151-80-32-156.muttsu.xyz;https://${API_HOST};g" /app/Contort/src/environments/environment.ts
RUN sed -i "s;https://localhost;https://${API_HOST};g" /app/Contort/src/environments/environment.ts
WORKDIR /app/Contort
RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=0 /app/Contort/dist/browser /usr/share/nginx/html

EXPOSE 80