FROM python:3.10-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg > /dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN apt-get --allow-unauthenticated update
RUN apt-get --allow-unauthenticated -y install postgresql-client-14
WORKDIR /app
RUN mkdir "/app/media"
RUN mkdir "/app/staticfiles"
RUN mkdir "/app/backup"
COPY . /app/

RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["gunicorn", "--workers=2", "contort.wsgi:application", "--bind", "0.0.0.0:8000", "--log-level=debug","--timeout", "300"]